### ISSUE TITLE
Add NIRSpec reduction capabilities (intermediate)

### ISSUE THREAD

**Issue by lkreidberg** [kevin218/Eureka#35] opened 2021-06-22 18:27 UTC

**Comment by AarynnCarter** [comment] 2021-06-26 00:33
An initial commit has just been made to the "nirspec" branch of Eureka following some work by myself and Eva-Maria Ahrer over the course of this week. 

With this Eureka now has the capability to read in NIRSpec *rateints.fits files and process them to a Stage 2 product using modified steps from the JWST pipeline. Primary reason of doing it this way is to avoid trimming of unilluminated pixels which are valuable for background and 1/f noise corrections. 

Still a good amount of work to be done, particularly:

**1) Incorporating a background subtraction method.**

Previous tests have shown that a simple median column-wise subtraction does a good job whilst also correcting for 1/f, so this is a good place to start. 

**2) Investigating DQ pixel masking. Important note from STScI:**

_"Most of those flags correspond to "hot" or "warm" pixels, which are populated according to the DQ array of the dark current reference file. Because the number of dark exposures taken on the ground was limited, it's likely many of these flags are spurious. We will obtain better data during Commissioning"_

Zafar Rustamkulov has looked into this for an upcoming paper on the NIRSpec data and is providing me some guidelines for DQ masking at some point next week. 

**3) Look at dispersion axis trimming**

Currently still struggling to figure out how to avoid any dispersion axis trimming by the pipeline. If this turns out to be unavoidable then we will need to provide on the fly modifications to the extraction apertures in the .ecf files to account for this trimming. 

**4) Test later stages of the pipeline** 

Continue processing the resulting data through the Eureka S3 pipeline to produce 1D spectra and S4 to produce light curves.

**Comment by kevin218** [comment] 2021-07-24 16:55
Updated NIRSpec pipeline pushed to GitHub.  Biggest changes are that I moved Stage 2 processing to a new folder (S2_calibrations) and changes the NaNs to INFs in the ERR array to get S3 working.

**Comment by taylorbell57** [comment] 2021-09-30 19:15
Hi all, I am currently testing out the S2_calibrations code that you wrote and have run into an issue in getting it to work with simulated NIRSpec data (specifically the file ERS_DATASIMv2_NIRSpec_PRISM_rateints.fits) on my laptop. While the file I'm testing the code on is only 2.7 GB in size, the assign_wcs step overflows my 12 GB of RAM and causes the code to terminate. I made some tweaks on the dev/tjb branch to undo the changes made specifically for the NIRSpec PRISM mode when the files being analyzed are not from NIRSpec so that I could test the code on a smaller MIRI simulation (miri_big_file_1_rateints.fits; 130 MB in size), and I can successfully run the code from start-to-finish with that much smaller file (note that this cuts out the assign_wcs step though).

Do any of you have any thoughts on why the assign_wcs step on line 86 of Eureka/eureka/S2_calibrations/s2_calibrate.py would cause a 2.7 GB file to require more than 12 GB of RAM? While I can probably deconstruct the file into many smaller files, it seems unusual that this step would bloat in RAM by more than a factor of 3.

**Comment by AarynnCarter** [comment] 2021-09-30 19:30
Hey Taylor,

I know the assign_wcs step is where the NIRSpec arrays were being trimmed to exclude a number of pixels (which we've tried to avoid). It might be that these new arrays are being loaded simultaneously with the original ones, but that still doesn't get us to a factor >3. It might be worth reaching out to the pipeline development team directly through the JWST Help Desk (they have been quite quick to respond in the past) to see if this is expected behaviour.

**Comment by taylorbell57** [comment] 2021-10-05 20:54
Has anyone worked out the relevant subarray region for NIRSpec for the Stage 3 ecf file? I'm going through and testing the integration of my Stage 2 outputs with Stage 3 before putting in a pull request, and I don't know what subarray region I should be using for NIRSpec

**Comment by kevin218** [comment] 2021-10-06 17:17
My NIRSpec reduction looks like garbage.  Anyone else getting better luck?
![fig3101-2D_LC](https://user-images.githubusercontent.com/21340541/136252213-801ede58-b704-403e-92d1-d6d2a8035ab4.png)

**Comment by AarynnCarter** [comment] 2021-10-06 17:24
Hey Kevin, that definitely doesn't look great! I attach a similar plot that Evie sent me a while ago, which I'm not sure is quite right either, but is much better than yours... 

This might be related to some issues I briefly touched on in our call. Let me have a deeper a look at this over the next few days, starting from the uncalibrated files, and I'll try to see if I can figure out what's going on. Sorry to hold up the NIRSpec side of things! 

![image](https://user-images.githubusercontent.com/23636747/136253020-59b46099-2b02-4992-9aa0-f26ee5910c07.png)

**Comment by kevin218** [comment] 2021-10-07 04:09
If I were to guess, I'd say the threshold constraints are too tight for optimal spectral extraction. Marking too many pixels as bad can really mess with the routine and produce worse results than straight summation.

**Comment by kevin218** [comment] 2021-10-07 04:14
My 2nd guess would be to use a different option for determining the spatial profile during optimal. I think the ecf file specifies meddata by default, which may not work well for the CV3 test data. Using the spline fitting option is probably the next best option.

**Comment by kevin218** [comment] 2021-11-03 20:45
I've been talking to Nestor about NIRSpec getting trimmed in the cross-dispersion direction and he wrote the following: 
> Are you sure the trimming happens at the assign_wcs step and not on the extract_2d step? For some subarrays/modes, the extract_2d step does trim the data (in prep for extract1d), but the assign_wcs step shouldn’t do this and that would be a bug. Could you double check?

Can someone confirm?

**Comment by AarynnCarter** [comment] 2021-11-03 21:06
Hey Kevin, looks like I got things mixed up when I said assign_wcs was doing the trimming. I'm almost certain it's the extract_2d step, just as Nestor mentioned.

**Comment by AarynnCarter** [comment] 2021-11-03 21:08
I realise now I got confused as it's during the assign_wcs step that certain parameters are set which define the trimming during the extract_2d step.

**Comment by taylorbell57** [comment] 2021-12-06 18:38
@kevin218 I would propose we close this issue as NIRCam, NIRSpec, and MIRI are now equally supported. Thoughts?

**Closed** 2021-12-16 19:52 UTC
Labels: enhancement, help wanted
