### ISSUE TITLE
Requirements for image_registration module

### ISSUE THREAD

**Issue by cpiaulet** [kevin218/Eureka#296] opened 2022-04-20 12:01 UTC
### What happened?

I just merged all the latest changes to the code to be able to test and publish my long-awaited PR, but I got the error
`ModuleNotFoundError: No module named 'image_registration'`

which I never got before. I am guessing this is a new requirement, which is in the file 
`eureka/S3_data_reduction/hst_scan.py`.

The issue is not fixed even when I install everything in the requirements.txt file. I can live without it for now as I don't need S3 but the issue happens whenever S3 is loaded for me. 

This wouldn't be so much of a problem if I _could_ install this module. Conda does not find it and pip gives me the following error traceback:

### Error traceback output

```
(jwst_eureka) caroline@Carolines-MacBook-Pro JWST % pip install image_registration
Collecting image_registration
  Using cached image_registration-0.2.5.tar.gz (2.7 MB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/caroline/opt/anaconda3/envs/jwst_eureka/bin/python /private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-standalone-pip-91ffu7qy/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-build-env-bu26tbbb/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools setuptools_scm wheel extension-helpers oldest-supported-numpy cython==0.29.14
       cwd: None
  Complete output (63 lines):
  Collecting setuptools
    Using cached setuptools-62.1.0-py3-none-any.whl (1.1 MB)
  Collecting setuptools_scm
    Using cached setuptools_scm-6.4.2-py3-none-any.whl (37 kB)
  Collecting wheel
    Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
  Collecting extension-helpers
    Using cached extension_helpers-1.0.0-py3-none-any.whl (20 kB)
  Collecting oldest-supported-numpy
    Using cached oldest_supported_numpy-2022.4.18-py3-none-any.whl (3.9 kB)
  Collecting cython==0.29.14
    Using cached Cython-0.29.14.tar.gz (2.1 MB)
      ERROR: Command errored out with exit status 1:
       command: /Users/caroline/opt/anaconda3/envs/jwst_eureka/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-install-xfvblzh1/cython_9d05b4ae91924608b651ec05bccfb668/setup.py'"'"'; __file__='"'"'/private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-install-xfvblzh1/cython_9d05b4ae91924608b651ec05bccfb668/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-pip-egg-info-uwl1zdps
           cwd: /private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-install-xfvblzh1/cython_9d05b4ae91924608b651ec05bccfb668/
      Complete output (43 lines):
      Unable to find pgen, not compiling formal grammar.
      running egg_info
      creating /private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-pip-egg-info-uwl1zdps/Cython.egg-info
      writing /private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-pip-egg-info-uwl1zdps/Cython.egg-info/PKG-INFO
      writing dependency_links to /private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-pip-egg-info-uwl1zdps/Cython.egg-info/dependency_links.txt
      writing entry points to /private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-pip-egg-info-uwl1zdps/Cython.egg-info/entry_points.txt
      writing top-level names to /private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-pip-egg-info-uwl1zdps/Cython.egg-info/top_level.txt
      writing manifest file '/private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-pip-egg-info-uwl1zdps/Cython.egg-info/SOURCES.txt'
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-install-xfvblzh1/cython_9d05b4ae91924608b651ec05bccfb668/setup.py", line 228, in <module>
          setup(
        File "/Users/caroline/opt/anaconda3/envs/jwst_eureka/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/Users/caroline/opt/anaconda3/envs/jwst_eureka/lib/python3.10/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/Users/caroline/opt/anaconda3/envs/jwst_eureka/lib/python3.10/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/Users/caroline/opt/anaconda3/envs/jwst_eureka/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/Users/caroline/opt/anaconda3/envs/jwst_eureka/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 299, in run
          self.find_sources()
        File "/Users/caroline/opt/anaconda3/envs/jwst_eureka/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 306, in find_sources
          mm.run()
        File "/Users/caroline/opt/anaconda3/envs/jwst_eureka/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 541, in run
          self.add_defaults()
        File "/Users/caroline/opt/anaconda3/envs/jwst_eureka/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 578, in add_defaults
          sdist.add_defaults(self)
        File "/Users/caroline/opt/anaconda3/envs/jwst_eureka/lib/python3.10/distutils/command/sdist.py", line 228, in add_defaults
          self._add_defaults_ext()
        File "/Users/caroline/opt/anaconda3/envs/jwst_eureka/lib/python3.10/distutils/command/sdist.py", line 311, in _add_defaults_ext
          build_ext = self.get_finalized_command('build_ext')
        File "/Users/caroline/opt/anaconda3/envs/jwst_eureka/lib/python3.10/distutils/cmd.py", line 299, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "/Users/caroline/opt/anaconda3/envs/jwst_eureka/lib/python3.10/distutils/cmd.py", line 107, in ensure_finalized
          self.finalize_options()
        File "/private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-install-xfvblzh1/cython_9d05b4ae91924608b651ec05bccfb668/Cython/Distutils/build_ext.py", line 20, in finalize_options
          self.distribution.ext_modules[:] = cythonize(
        File "/private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-install-xfvblzh1/cython_9d05b4ae91924608b651ec05bccfb668/Cython/Build/Dependencies.py", line 959, in cythonize
          module_list, module_metadata = create_extension_list(
        File "/private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-install-xfvblzh1/cython_9d05b4ae91924608b651ec05bccfb668/Cython/Build/Dependencies.py", line 752, in create_extension_list
          elif isinstance(patterns, basestring) or not isinstance(patterns, collections.Iterable):
      AttributeError: module 'collections' has no attribute 'Iterable'
      ----------------------------------------
  WARNING: Discarding https://files.pythonhosted.org/packages/9c/9b/706dac7338c2860cd063a28cdbf5e9670995eaea408abbf2e88ba070d90d/Cython-0.29.14.tar.gz#sha256=e4d6bb8703d0319eb04b7319b12ea41580df44fd84d83ccda13ea463c6801414 (from https://pypi.org/simple/cython/) (requires-python:>=2.6, !=3.0.*, !=3.1.*, !=3.2.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  ERROR: Could not find a version that satisfies the requirement cython==0.29.14 (from versions: 0.9.6.5, 0.9.6.6, 0.9.6.7, 0.9.6.8, 0.9.6.10b0, 0.9.6.10, 0.9.6.10.1, 0.9.6.11b0, 0.9.6.11, 0.9.6.12, 0.9.6.13, 0.9.6.13.1, 0.9.6.14, 0.9.8, 0.9.8.1, 0.9.8.1.1, 0.10, 0.10.1, 0.10.2, 0.10.3, 0.11, 0.11.1, 0.11.2, 0.11.3, 0.12, 0.12.1, 0.13, 0.14, 0.14.1, 0.15, 0.15.1, 0.16, 0.17, 0.17.1, 0.17.2, 0.17.3, 0.17.4, 0.18, 0.19, 0.19.1, 0.19.2, 0.20, 0.20.1, 0.20.2, 0.21, 0.21.1, 0.21.2, 0.22, 0.22.1, 0.23, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.23.5, 0.24, 0.24.1, 0.25, 0.25.1, 0.25.2, 0.26, 0.26.1, 0.27, 0.27.1, 0.27.2, 0.27.3, 0.28, 0.28.1, 0.28.2, 0.28.3, 0.28.4, 0.28.5, 0.28.6, 0.29, 0.29.1, 0.29.2, 0.29.3, 0.29.4, 0.29.5, 0.29.6, 0.29.7, 0.29.8, 0.29.9, 0.29.10, 0.29.11, 0.29.12, 0.29.13, 0.29.14, 0.29.15, 0.29.16, 0.29.17, 0.29.18, 0.29.19, 0.29.20, 0.29.21, 0.29.22, 0.29.23, 0.29.24, 0.29.25, 0.29.26, 0.29.27, 0.29.28, 3.0a1, 3.0a2, 3.0a3, 3.0a4, 3.0a5, 3.0a6, 3.0a7, 3.0.0a8, 3.0.0a9, 3.0.0a10)
  ERROR: No matching distribution found for cython==0.29.14
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/86/7f/39340623d4a62db100e20ac3138f832ff1d22cba0c829189f9d326953198/image_registration-0.2.5.tar.gz#sha256=18c945c88c5c4540da798d38252b1baa8e45e3474c256c4a7f54e52c3c8a2e87 (from https://pypi.org/simple/image-registration/) (requires-python:>=3.7). Command errored out with exit status 1: /Users/caroline/opt/anaconda3/envs/jwst_eureka/bin/python /private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-standalone-pip-91ffu7qy/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-build-env-bu26tbbb/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools setuptools_scm wheel extension-helpers oldest-supported-numpy cython==0.29.14 Check the logs for full command output.
  Using cached image_registration-0.2.4.tar.gz (2.8 MB)
    ERROR: Command errored out with exit status 1:
     command: /Users/caroline/opt/anaconda3/envs/jwst_eureka/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-install-j5d2pq52/image-registration_918059eef5ad4e47b6209ad989c05c27/setup.py'"'"'; __file__='"'"'/private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-install-j5d2pq52/image-registration_918059eef5ad4e47b6209ad989c05c27/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-pip-egg-info-ps35i7if
         cwd: /private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-install-j5d2pq52/image-registration_918059eef5ad4e47b6209ad989c05c27/
    Complete output (1 lines):
    error in image_registration setup command: use_2to3 is invalid.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/2a/6c/e1b96a53e6f3a6b2afa10623b1e5f9195a54bf07a7dd06ce0cc0da50b6ee/image_registration-0.2.4.tar.gz#sha256=a5416a2d91d3a8f43a089256ef3f959792fba69d03370b9d747120ea2dc0e77f (from https://pypi.org/simple/image-registration/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached image_registration-0.2.3.tar.gz (54 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/caroline/opt/anaconda3/envs/jwst_eureka/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-install-j5d2pq52/image-registration_29113cb83d894b79bda372055cb3a0b7/setup.py'"'"'; __file__='"'"'/private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-install-j5d2pq52/image-registration_29113cb83d894b79bda372055cb3a0b7/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-pip-egg-info-ems2_qmt
         cwd: /private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-install-j5d2pq52/image-registration_29113cb83d894b79bda372055cb3a0b7/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-install-j5d2pq52/image-registration_29113cb83d894b79bda372055cb3a0b7/setup.py", line 8, in <module>
        import ah_bootstrap
    ModuleNotFoundError: No module named 'ah_bootstrap'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/43/5d/b9f8cf74b11fe0fb9396ec97a902a0b3afc95ea16c2cf9a938c46d55710a/image_registration-0.2.3.tar.gz#sha256=473b298c72db127d861e3d7e91d369abb7a28b2ffbe04f827650247e6cf481d9 (from https://pypi.org/simple/image-registration/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached image_registration-0.2.2.tar.gz (54 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/caroline/opt/anaconda3/envs/jwst_eureka/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-install-j5d2pq52/image-registration_8484f46819c041d39009b78260c4545d/setup.py'"'"'; __file__='"'"'/private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-install-j5d2pq52/image-registration_8484f46819c041d39009b78260c4545d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-pip-egg-info-qbmqvj38
         cwd: /private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-install-j5d2pq52/image-registration_8484f46819c041d39009b78260c4545d/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-install-j5d2pq52/image-registration_8484f46819c041d39009b78260c4545d/setup.py", line 8, in <module>
        import ah_bootstrap
    ModuleNotFoundError: No module named 'ah_bootstrap'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/bd/c5/f753d26d13f6525f2eb318d09c0d547e8b97d98ade3c43448cbce681e9e9/image_registration-0.2.2.tar.gz#sha256=d953cdb690db64a4ec03fb4fd65bf9461db4fe1885611455d0ec534a12cc4ba2 (from https://pypi.org/simple/image-registration/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached image_registration-0.2.1.tar.gz (42 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/caroline/opt/anaconda3/envs/jwst_eureka/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-install-j5d2pq52/image-registration_579b93c7782c402cab1810e1623378c0/setup.py'"'"'; __file__='"'"'/private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-install-j5d2pq52/image-registration_579b93c7782c402cab1810e1623378c0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-pip-egg-info-yvspxjvl
         cwd: /private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-install-j5d2pq52/image-registration_579b93c7782c402cab1810e1623378c0/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-install-j5d2pq52/image-registration_579b93c7782c402cab1810e1623378c0/setup.py", line 28, in <module>
        execfile('image_registration/version.py')
    NameError: name 'execfile' is not defined
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/2e/92/c53d46f136c0e5c588d5bef27937066de2a21abd2c05620b9b9cce500597/image_registration-0.2.1.tar.gz#sha256=e30506daaed8ec9a043f55073d32f5a07ecc3310e78ba1bf43ad7c3d06135033 (from https://pypi.org/simple/image-registration/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached image_registration-0.2.tar.gz (41 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/caroline/opt/anaconda3/envs/jwst_eureka/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-install-j5d2pq52/image-registration_72de61629ce8464597555d0c9cdbcdfb/setup.py'"'"'; __file__='"'"'/private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-install-j5d2pq52/image-registration_72de61629ce8464597555d0c9cdbcdfb/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-pip-egg-info-8cl4aul8
         cwd: /private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-install-j5d2pq52/image-registration_72de61629ce8464597555d0c9cdbcdfb/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/84/bn_jkl1s46nb1x7pt2_r54_80000gn/T/pip-install-j5d2pq52/image-registration_72de61629ce8464597555d0c9cdbcdfb/setup.py", line 12, in <module>
        with open('CHANGES') as file:
    FileNotFoundError: [Errno 2] No such file or directory: 'CHANGES'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/75/ee/e5345f7607934847a4d1be15d363810ee0d0714562fc7e3f9c7f2a1cee77/image_registration-0.2.tar.gz#sha256=617352cdae94eed66dd30310c4185119e6ade2d48a59a0c582f328dbb9966737 (from https://pypi.org/simple/image-registration/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement image_registration (from versions: 0.2, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5)
ERROR: No matching distribution found for image_registration
```

### What operating system are you using?

Mac OS Monterey 12.0.1

### What version of Python are you running?

Python 3.10.0

### What Python packages do you have installed?

```
# packages in environment at /Users/caroline/opt/anaconda3/envs/jwst_eureka:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   pypi_0    pypi
appnope                   0.1.2                    pypi_0    pypi
asdf                      2.8.1                    pypi_0    pypi
asdf-astropy              0.1.2                    pypi_0    pypi
asdf-coordinates-schemas  0.1.0                    pypi_0    pypi
asdf-transform-schemas    0.2.0                    pypi_0    pypi
asdf-wcs-schemas          0.1.1                    pypi_0    pypi
asteval                   0.9.26                   pypi_0    pypi
astropy                   5.0.1                    pypi_0    pypi
astropy-healpix           0.6                      pypi_0    pypi
astroquery                0.4.5                    pypi_0    pypi
astroscrappy              1.1.0                    pypi_0    pypi
asttokens                 2.0.5                    pypi_0    pypi
attrs                     21.4.0             pyhd3eb1b0_0  
babel                     2.9.1                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
batman-package            2.4.8                    pypi_0    pypi
bayesicfitting            2.8.1                    pypi_0    pypi
beautifulsoup4            4.10.0                   pypi_0    pypi
black                     22.1.0                   pypi_0    pypi
bleach                    4.1.0                    pypi_0    pypi
bokeh                     2.4.2                    pypi_0    pypi
bzip2                     1.0.8                h1de35cc_0  
ca-certificates           2021.10.26           hecd8cb5_2  
ccdproc                   2.3.0                    pypi_0    pypi
certifi                   2021.10.8                pypi_0    pypi
charset-normalizer        2.0.11                   pypi_0    pypi
click                     8.0.3                    pypi_0    pypi
commonmark                0.9.1                    pypi_0    pypi
corner                    2.2.1                    pypi_0    pypi
crds                      11.6.0                   pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.25         py310he9d5cce_0  
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
docutils                  0.17.1                   pypi_0    pypi
drizzle                   1.13.4                   pypi_0    pypi
dynesty                   1.1                      pypi_0    pypi
emcee                     3.1.1                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
executing                 0.8.2                    pypi_0    pypi
extension-helpers         0.1                      pypi_0    pypi
filelock                  3.4.2                    pypi_0    pypi
fonttools                 4.29.1                   pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
george                    0.4.0                    pypi_0    pypi
gwcs                      0.18.0                   pypi_0    pypi
h5py                      3.6.0                    pypi_0    pypi
html5lib                  1.1                      pypi_0    pypi
idna                      3.3                      pypi_0    pypi
imageio                   2.14.1                   pypi_0    pypi
imagesize                 1.3.0                    pypi_0    pypi
importlib-metadata        4.10.1                   pypi_0    pypi
iniconfig                 1.1.1              pyhd3eb1b0_0  
ipython                   8.0.1                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jedi                      0.18.1                   pypi_0    pypi
jinja2                    3.0.3                    pypi_0    pypi
jmespath                  0.10.0                   pypi_0    pypi
jsonschema                3.2.0                    pypi_0    pypi
jupyter-client            7.1.2                    pypi_0    pypi
jupyter-core              4.9.1                    pypi_0    pypi
jupyterlab-pygments       0.1.2                    pypi_0    pypi
jwst                      1.3.3                    pypi_0    pypi
keyring                   23.5.0                   pypi_0    pypi
kiwisolver                1.3.2                    pypi_0    pypi
libcxx                    12.0.0               h2f01273_0  
libffi                    3.3                  hb1e8313_2  
lmfit                     1.0.3                    pypi_0    pypi
lxml                      4.7.1                    pypi_0    pypi
markdown-it-py            2.0.1                    pypi_0    pypi
markupsafe                2.0.1                    pypi_0    pypi
matplotlib                3.5.1                    pypi_0    pypi
matplotlib-inline         0.1.3                    pypi_0    pypi
mdit-py-plugins           0.3.0                    pypi_0    pypi
mdurl                     0.1.0                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
more-itertools            8.12.0             pyhd3eb1b0_0  
mypy-extensions           0.4.3                    pypi_0    pypi
myst-parser               0.16.1                   pypi_0    pypi
nbclient                  0.5.10                   pypi_0    pypi
nbconvert                 6.4.1                    pypi_0    pypi
nbformat                  5.1.3                    pypi_0    pypi
nbsphinx                  0.8.8                    pypi_0    pypi
ncurses                   6.3                  hca72f7f_2  
nest-asyncio              1.5.4                    pypi_0    pypi
networkx                  2.6.3                    pypi_0    pypi
numpy                     1.22.2                   pypi_0    pypi
numpydoc                  1.2                      pypi_0    pypi
openssl                   1.1.1m               hca72f7f_0  
packaging                 21.3               pyhd3eb1b0_0  
pandas                    1.4.0                    pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parsley                   1.3                      pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pathspec                  0.9.0                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
photutils                 1.1.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.0.1                    pypi_0    pypi
pip                       21.2.4          py310hecd8cb5_0  
platformdirs              2.4.1                    pypi_0    pypi
pluggy                    0.13.1          py310hecd8cb5_0  
poppy                     1.0.2                    pypi_0    pypi
prompt-toolkit            3.0.26                   pypi_0    pypi
psutil                    5.9.0                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
py                        1.11.0                   pypi_0    pypi
pyerfa                    2.0.0.1                  pypi_0    pypi
pygments                  2.11.2                   pypi_0    pypi
pyparsing                 3.0.7                    pypi_0    pypi
pyrsistent                0.18.1                   pypi_0    pypi
pysynphot                 2.0.0                    pypi_0    pypi
pytest                    7.0.0                    pypi_0    pypi
python                    3.10.0               hdfd78df_3  
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2021.3                   pypi_0    pypi
pyvo                      1.2.1                    pypi_0    pypi
pywavelets                1.2.0                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     22.3.0                   pypi_0    pypi
readline                  8.1.2                hca72f7f_1  
recommonmark              0.7.1                    pypi_0    pypi
reproject                 0.8                      pypi_0    pypi
requests                  2.27.1                   pypi_0    pypi
scikit-image              0.19.1                   pypi_0    pypi
scipy                     1.8.0                    pypi_0    pypi
semantic-version          2.8.5                    pypi_0    pypi
setuptools                58.0.4          py310hecd8cb5_0  
six                       1.16.0                   pypi_0    pypi
snowballstemmer           2.2.0                    pypi_0    pypi
soupsieve                 2.3.1                    pypi_0    pypi
spherical-geometry        1.2.22                   pypi_0    pypi
sphinx                    4.4.0                    pypi_0    pypi
sphinx-rtd-theme          1.0.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlite                    3.37.0               h707629a_0  
stack-data                0.1.4                    pypi_0    pypi
stcal                     0.6.0                    pypi_0    pypi
stdatamodels              0.2.3                    pypi_0    pypi
stpipe                    0.2.0                    pypi_0    pypi
stsci-image               2.3.5                    pypi_0    pypi
stsci-imagestats          1.6.3                    pypi_0    pypi
stsci-stimage             0.2.5                    pypi_0    pypi
svo-filters               0.4.1                    pypi_0    pypi
testpath                  0.5.0                    pypi_0    pypi
tifffile                  2022.2.2                 pypi_0    pypi
tk                        8.6.11               h7bc2e8c_0  
toml                      0.10.2             pyhd3eb1b0_0  
tomli                     2.0.0                    pypi_0    pypi
tornado                   6.1                      pypi_0    pypi
tqdm                      4.62.3                   pypi_0    pypi
traitlets                 5.1.1                    pypi_0    pypi
tweakwcs                  0.7.3                    pypi_0    pypi
typing-extensions         4.0.1                    pypi_0    pypi
tzdata                    2021e                hda174b7_0  
uncertainties             3.1.6                    pypi_0    pypi
urllib3                   1.26.8                   pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.2.5                h1de35cc_0  
zipp                      3.7.0                    pypi_0    pypi
zlib                      1.2.11               h4dc903c_4 
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment] 2022-04-21 22:17
@cpiaulet can you try updating your code against the main branch since this issue should have already been resolved. You shouldn't need to have image_registration installed anymore to lead in Stage 3, but if you want to install it you can do the `pip install .[hst]` that Sebastian mentioned

**Comment by taylorbell57** [comment] 2022-04-27 01:12
Hearing nothing and having confirmed that this does not appear to be an issue using a fresh installation in a Docker container, I'm going to close this issue now. Feel free to reopen the issue if it is still present for you though

**Closed by taylorbell57** 2022-04-27 01:12 UTC
