### ISSUE TITLE
TypeError bug when running Stage 3

### ISSUE THREAD

**Issue by Witchblade101** [kevin218/Eureka#233] opened 2022-03-25 18:13 UTC
I installed Eureka on the morning of the last day of the ERS Data Challenge and started processing on Stage 1 NRS simulated data. Everything looked good, but it crashed when it reached Stage 3:

Starting Stage 3 Reduction

Input directory: /Users/dlong/2022-DataShowcase/NIRSpec/Stage2/S2_2022-03-23_wasp39b_run2/
Output directory: /Users/dlong/2022-DataShowcase/NIRSpec/Stage3/S3_2022-03-23_wasp39b_ap6_bg7_run1/
Using ap=6, bg=7
  WARNING: Manually setting INTSTART to 1 and INTEND to NINTS
  WARNING: The timestamps for the simulated NIRSpec data are currently hardcoded because they are not in the .fits files themselves
  WARNING: Manually changing NaNs from DATA and ERR arrays to 0 for the CV3 data
2022-03-23 17:31:04,601 - stpipe - WARNING - /Users/dlong/miniconda3/envs/eureka/lib/python3.9/site-packages/numpy/core/fromnumeric.py:3474: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,

2022-03-23 17:31:04,603 - stpipe - WARNING - /Users/dlong/miniconda3/envs/eureka/lib/python3.9/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in true_divide
  ret = ret.dtype.type(ret / rcount)

2022-03-23 17:31:17,164 - stpipe - WARNING - /Users/dlong/miniconda3/envs/eureka/lib/python3.9/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

2022-03-24 06:00:12,328 - stpipe - WARNING - /Users/dlong/miniconda3/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/optspex.py:153: RuntimeWarning: invalid value encountered in true_divide
  profile /= np.sum(profile, axis=0)

2022-03-24 14:51:37,024 - stpipe - WARNING - /Users/dlong/miniconda3/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/optspex.py:505: RuntimeWarning: divide by zero encountered in true_divide
  stdevs      = np.abs(subdata - expected)*submask / np.sqrt(variance)

2022-03-24 14:51:37,025 - stpipe - WARNING - /Users/dlong/miniconda3/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/optspex.py:556: RuntimeWarning: invalid value encountered in true_divide
  denom    = np.sum(profile*profile*submask/variance, axis=0)

2022-03-24 14:51:37,025 - stpipe - WARNING - /Users/dlong/miniconda3/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/optspex.py:558: RuntimeWarning: invalid value encountered in true_divide
  spectrum = np.sum(profile*submask*subdata/variance, axis=0) / denom

Traceback (most recent call last):
  File "/Users/dlong/2022-DataShowcase/NIRSpec/JWST/run_eureka.py", line 22, in <module>
    s3_meta = s3.reduceJWST(eventlabel, ecf_path=ecf_path, s2_meta=s2_meta)
  File "/Users/dlong/miniconda3/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/s3_reduce.py", line 315, in reduceJWST
    plots_s3.optimal_spectrum(data, meta, n)
  File "/Users/dlong/miniconda3/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/plots_s3.py", line 111, in optimal_spectrum
    plt.errorbar(range(subnx), optspec[n], opterr[n], fmt='-', color='C2', ecolor='C2', label='Optimal Spec')
  File "/Users/dlong/miniconda3/envs/eureka/lib/python3.9/site-packages/matplotlib/pyplot.py", line 2509, in errorbar
    return gca().errorbar(
  File "/Users/dlong/miniconda3/envs/eureka/lib/python3.9/site-packages/matplotlib/__init__.py", line 1412, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/Users/dlong/miniconda3/envs/eureka/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 3467, in errorbar
    barcols.append(lines_func(
  File "/Users/dlong/miniconda3/envs/eureka/lib/python3.9/site-packages/matplotlib/__init__.py", line 1412, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/Users/dlong/miniconda3/envs/eureka/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 1142, in vlines
    minx = x.min()
  File "/Users/dlong/miniconda3/envs/eureka/lib/python3.9/site-packages/numpy/ma/core.py", line 5703, in min
    result = self.filled(fill_value).min(
  File "/Users/dlong/miniconda3/envs/eureka/lib/python3.9/site-packages/numpy/core/_methods.py", line 44, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
TypeError: '<=' not supported between instances of 'str' and 'int'
(eureka) minmei:JWST dlong$

**Comment by taylorbell57** [comment] 2022-03-25 18:19
This is a duplicate of #228 and #108 - I have a patch implemented for that which should hopefully be merged into main in a few days. In the meantime, if you set isplots to 1 in your Stage 3 ECF, then that buggy plot will be skipped and you can move on to the later stages

**Comment by taylorbell57** [comment] 2022-03-25 18:20
Closing this for now to avoid too many duplicate issues, but I recommend you subscribe to those issues if you want an email update once the bug is fixed

**Comment by Witchblade101** [comment] 2022-03-25 18:21
Thanks, Taylor. I looked but I didn't find those. I'll try out isplots = 1 when I get the chance.

**Closed by taylorbell57** 2022-03-25 18:20 UTC
Labels: duplicate
