### ISSUE TITLE
Running S3 with multiple threads seems to be slower than one thread

### ISSUE THREAD

**Issue by taylorbell57** [kevin218/Eureka#97] opened 2022-01-27 00:14 UTC
When testing the new jwst v1.3.3 I noticed that the background subtraction step in S3 ([here](https://github.com/kevin218/Eureka/blob/fc3c4c9cf972b9fc1896133af708349edc54c6b9/eureka/S3_data_reduction/background.py#L65-L73)) was requiring 6 seconds per iteration with 14 cpu threads, but when I tried to run it with only 1 cpu thread it only took 2 seconds per iteration. I can imagine the runtime not scaling linearly with the cpu threads, but running slower seems very unintuitive and is obviously a bad sign. We'll need to see if this is related to my other multithreading issue (#92) or if the there is a larger issue with multithreading here.

**Comment by kevin218** [comment] 2022-02-09 16:04
There comes a point when adding CPUs doesn't actually speed things up because a non-parallelized step becomes the limiting factor.  For example, with my WFC3 code, having more than 6 cores didn't improve the speed because writing the results to pieces of an array became the limiting factor.

**Comment by taylorbell57** [comment] 2022-02-09 19:14
I've encountered that before, but I don't think running this code in parallel should become slower than running it in a single thread - just that the speed improvement should have diminishing returns with increasing threads. I'll check if 2 threads is faster than 1 in a bit to see if there is any improvement there

**Comment by taylorbell57** [comment] 2022-02-10 01:09
Hmm, well I'm not sure what caused the issue before for me, but below are the results of some tests I just ran with a freshly setup conda environment made using the new `pip install .` method which behave basically exactly as I would expect. Perhaps whatever environment I was using before had some sub-optimal version of numpy or astropy or something?

For **NIRSpec** data, I currently get 23 it/sec for 1 thread, 43 it/sec for 2 threads, 78 it/sec for 4 threads, 130 it/sec for 8 threads, and 135 it/sec for 14 threads.

For **MIRI** data, I get 29 it/sec for 1 thread, I get 31 it/sec for 2 threads, 40 it/sec for 4 threads, 43 it/sec for 8 threads, and 33 it/sec for 14 threads.

For **NIRCam** I get 2 sec/it for 1 thread, 1 it/sec for 2 threads, 2 it/sec for 4 threads, 3 it/sec for 8 threads, and 3 it/sec for 14 threads.

One reason NIRSpec's performance is better than the others is that there is just one huge file for that dataset, so the code spends less time initializing the thread pool per integration while MIRI and NIRCam have many files so the thread pool needs to spawn many times. This can also be seen for MIRI where moving from 8 to 14 threads gave slightly worse performance since the thread pool took longer to spawn that particular time. I think the rest of the runtime differences are likely driven by pixel counts, with NIRSpec having 7,350 pixels, MIRI having 14,490 pixels, and NIRCam having 94,400 pixels.

Closing this issue now since the issue cannot be reproduced.

**Comment by taylorbell57** [comment] 2022-02-18 19:00
Well this issue has once again popped up for me... I get ~2s/it for NIRCam with 1 thread and ~8+ seconds/it for my multithreading attempts. Reopening the issue in case others know how to deal with this. My computer isn't doing anything intensive at the same time or anything and I should have plenty of RAM available.

**Comment by jbrande** [comment] 2022-02-28 03:13
Adding onto this, on the full NIRSpec dataset I seem to be getting 26 it/sec with 1 cpu and 6 it/sec with 16 cpus.

**Comment by AarynnCarter** [comment] 2022-03-18 17:13
Perhaps the most egregious yet, I have ~50 it/s for 1 cpu, and ~0.02 it/s for 4 cpus. This is for the full NIRSpec dataset, bg_deg=0.

**Comment by AarynnCarter** [comment] 2022-04-05 22:14
Okay I just took a look at this and have figured out a fix. For reference:

```
# PREVIOUS METHOD
for n in range(meta.int_start,meta.n_int):
        args_list.append((data, meta, n, isplots))
jobs = [pool.apply_async(func=inst.fit_bg, args=(*args,), callback=writeBG) for args in args_list]

# NEW METHOD 
jobs = [pool.apply_async(func=inst.fit_bg, args=(data.subdata[n], data.submask[n], n, meta, isplots,), callback=writeBG) for n in range(meta.int_start,meta.n_int)]
```

I think the issue is that the `args_list` being created has the data array repeated NINT times, which when we are looking at a ~8192x512x32 array like NIRSpec, is a huge amount of memory. By passing this to async and having it extract all of these identical arrays over and over it just ends up slowing things down more than speeding them up. 

The new method bypasses this by directly adjusting the `fit_bg` function to accept individual frames/masks, rather than the full data array. For NIRCam / NIRSpec / MIRI this was pretty straightforward as it used the` background.fitbg()` function which took individual frames anyway. 

These changes are now on the `s3mp` branch, which was (erroneously) sprouted from my dev/alc branch, which is ahead of main by a couple of commits. 

For NIRISS / WFC3, @afeinstein20, @kevin218, @taylorbell57, maybe you could adjust the other background functions to accept individual frames also? In the meantime, I have preserved the functionality for the old multiprocessing (just for these instruments), so the branch could also be merged as is.

**Comment by taylorbell57** [comment] 2022-04-06 16:31
I can tweak the WFC3 code directly in that s3mp branch if you're okay with that? Very excited to test this out - your solution makes a lot of sense to me!

**Comment by AarynnCarter** [comment] 2022-04-06 17:20
@taylorbell57 Definitely, go for it! :)

**Comment by taylorbell57** [comment] 2022-04-06 17:27
Hmm, so it seems the overhead of opening and closing a pool of thread workers is not worthwhile for the most recent simulated MIRI observations or for the WASP-12b WFC3 observations I have on hand which have very few integrations per file. For WFC3, it already takes less than a second to do the background subtraction, and for the newest MIRI simulations there are far fewer integrations per file than the old MIRI simulations so the overhead ends up costing more than the speed-up gained over the small number of integrations per file. That doesn't mean your edits are wrong though --- they make considerable sense to me --- it's just that multiprocessing isn't worthwhile for some instruments which would be good to add to the documentation somewhere at some point.

My adjustments for WFC3 are now pushed to that branch FYI

**Comment by taylorbell57** [comment] 2022-04-06 17:36
Given how small the Stage 2 files should be (well below 1 GB), it might be worth editing the S3 code to load in multiple Stage 2 output files at once (e.g. say 5 files or 20 files depending on the filesize vs RAM size and/or user settings in the S3 ECF). This would increase RAM utilization but may allow for more rapid performance overall (especially if it means we can benefit more from parallelization). This would also have the added benefit of allowing the WFC3 code to do per-pixel sigma clipping over a longer time domain than just one file which is something Kevin and I have wanted to add for a while. Likely not a high priority, but something that would be good to add sooner than later

**Comment by AarynnCarter** [comment] 2022-04-06 20:12
Do you know if the Stage 2 file size is ~independent between instruments? I really like the idea but I'm a little wary of building things like this before we know what the actual data look like.

**Comment by taylorbell57** [comment] 2022-04-06 20:26
My understanding is that the uncal files should all be ~1 GB in size or so (that's off the top of my head). So the calints files will vary by instrument some but for MIRI they end up being somewhere in the range of 10-100 MB (again, off the top of my head). On idea is that we could write something that checks for the available RAM and figures out how many files can fit in some user-provided percentage of the RAM or something. I'd want to double check the expected file sizes and all that before actually adding that feature, but it'd be worthwhile either way for WFC3

**Comment by taylorbell57** [comment] 2022-04-16 00:06
@AarynnCarter, do you want to open a PR based on your edits addressing this issue? And once that's started, @afeinstein20  or I can work on making the required tweaks to the NIRISS background subtraction function

**Closed** 2022-04-19 18:42 UTC
Labels: bug, help wanted
