### ISSUE TITLE
look into replacing ecf files with yaml files

### ISSUE THREAD

**Issue by lkreidberg** [kevin218/Eureka#239] opened 2022-03-28 16:22 UTC
ecf files are buggy (there are issues with spaces and tabs). -- are we reinventing the wheel? would a yaml file be better?

**Comment by taylorbell57** [comment] 2022-03-28 16:57
While all currently known bugs with ECF/EPF files should be resolved with PR #234 (no longer any issues with spaces or tabs), discussing the potential for changing to YAML rather than basically making a YAYAML (yet another, yet another markup language) may still be worthwhile in the future.

**Comment by taylorbell57** [comment] 2024-02-06 02:19
@kevin218, what do you feel about changing from ECFs to YAMLs? If we're going to make this change, v1 is likely the time to do it. I don't feel strongly either way, but I also don't feel like the work put into this would solve any problems we're currently experiencing. The one possible exception is that in S1 setting `ramp_fit_max_cores all` ends up with `all` being interpreted as the built-in function `all()` rather than the intended `'all'`; as a result, some special strings like that occasionally need to be escaped, while most values do end up being interpreted correctly. I'm not sure that YAML will resolve that issue, but I also don't know that it won't.

Ultimately, I'm not overly inclined to put the effort into make the change from ECFs and EPFs to YAMLs, but I'm also not opposed to the idea if you think it's worthwhile.

**Comment by kevin218** [comment] 2024-02-07 00:00
I think we should keep the ECFs. You're right in that it isn't really solving a problem, and it may even introduce new ones due to unexpected behavior. 

Let's spend our limited resources on more important issues.

**Closed** 2024-02-07 00:01 UTC
Labels: future work
