### ISSUE TITLE
[Bug]: Stage 1 Runs, But Seemingly Does Not Produce Necessary Files for Stage 2

### ISSUE THREAD

**Issue by nascarsdale** [kevin218/Eureka#264] opened 2022-04-06 00:24 UTC
### Contact Details

nscarsda@ucsc.edu

### Instrument

NIRCam (Stages 1-3)

### What happened?

I am running Eureka in a conda environment created using the official [guide](https://eurekadocs.readthedocs.io/en/latest/installation.html#installation) (pip install method). I downloaded the uncalibrated NIRCam data from [box](https://stsci.app.box.com/s/tj1jnivn9ekiyhecl5up7mkg8xrd1htl/folder/154382834528) (only 1 file for testing purposes) and attempted to reduce it. Stage 1 ran without a hitch, however stage 2 immediately errors out. The message is included in full below, however I believe the salient portion is: 

> `AssertionError: Unable to find any "rateints.fits" files in the inputdir: "/home/nicholas/science/jwst-cycle-1-and-prep/NIRSpec/Eureka_reductions/Stage1/"`

Please disregard the fact that for some unknowable reason I chose to put my NIRCam data in the NIRSpec folder. The contents of the /.../Eureka_reductions/Uncal folder ("inputdir" for Stage 1) are:

> jw01366002001_01101_00002-seg001_nrca5_uncal.fits  

> jwdata0010010_11010_0001_NRS1_uncal_updatedHDR_MOD_injected_rateints.fits

It seems like something is happening that causes stage 2 not to have the necessary file. This is perhaps related to the unclosed log file, or perhaps there is some critical file that I don't have downloaded. I have attached the full output from my command `python run_eureka.py` below; if it is helpful, I am doing all this on Ubuntu 18.04. Please let me know if there's any other info I can provide to help debug this! 

[full_output.txt](https://github.com/kevin218/Eureka/files/8422590/full_output.txt)

### Error traceback output

**lots of stage 1 info, then:**
2022-04-05 15:23:21,066 - stpipe.EurekaS1Pipeline - INFO - Step EurekaS1Pipeline done

Total time (min): 16.95
Saving Metadata

2022-04-05 15:23:21,075 - stpipe - WARNING - /home/nicholas/science/jwst-cycle-1-and-prep/WASP-39b-Eureka/run_eureka.py:17: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/nicholas/science/jwst-cycle-1-and-prep/NIRSpec/Eureka_reductions/Stage1/S1_2022-04-05_wasp39b_run2//S1_wasp39b.log' mode='w' encoding='UTF-8'>
  s1_meta = s1.rampfitJWST(eventlabel, ecf_path=ecf_path)

**Stage 2 immediately errors out with the following message:**
Starting Stage 2 Reduction
Copying S2 control file
Traceback (most recent call last):
  File "/home/nicholas/science/jwst-cycle-1-and-prep/WASP-39b-Eureka/run_eureka.py", line 19, in <module>
    s2_meta = s2.calibrateJWST(eventlabel, ecf_path=ecf_path)
  File "/home/nicholas/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S2_calibrations/s2_calibrate.py", line 87, in calibrateJWST
    raise AssertionError(f'Unable to find any "{meta.suffix}.fits" files in the inputdir: \n"{meta.inputdir}"!')
AssertionError: Unable to find any "rateints.fits" files in the inputdir:
"/home/nicholas/science/jwst-cycle-1-and-prep/NIRSpec/Eureka_reductions/Stage1/"!
2022-04-05 15:23:21,154 - stpipe - WARNING - sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/nicholas/science/jwst-cycle-1-and-prep/NIRSpec/Eureka_reductions/Stage2/S2_2022-04-05_wasp39b_run2/S2_wasp39b.log' mode='w' encoding='UTF-8'>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment] 2022-04-06 00:41
Ah yes, this is related to issue #125. If you now edit run_eureka.py and comment out the s1.rampfit line (and the s1_meta input to s2), then you should be able to run the run_eureka.py file again and it will start from the Stage 1 outputs you've already produced. As this is a duplicate of #125, I am going to close this particular issue but thanks for the reminder that this should be addressed soon!

**Closed by taylorbell57** 2022-04-06 00:41 UTC
Labels: bug, duplicate

**Comment by nascarsdale** [comment] 2022-04-06 23:00
Hi Taylor, 

Thanks so much for the response! After changing the relevant section of the run_eureka.py file to:

```
if __name__ == '__main__':
        #fixing disconnect between S1 and S2; remove comment if this is a first run
        #s1_meta = s1.rampfitJWST(eventlabel, ecf_path=ecf_path)

        s2_meta = s2.calibrateJWST(eventlabel, ecf_path=ecf_path)
```
I still receive the error: 

> Starting Stage 2 Reduction
Copying S2 control file
Traceback (most recent call last):
  File "/home/nicholas/science/jwst-cycle-1-and-prep/WASP-39b-Eureka/run_eureka.py", line 20, in <module>
    s2_meta = s2.calibrateJWST(eventlabel, ecf_path=ecf_path)
  File "/home/nicholas/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S2_calibrations/s2_calibrate.py", line 87, in calibrateJWST
    raise AssertionError(f'Unable to find any "{meta.suffix}.fits" files in the inputdir: \n"{meta.inputdir}"!')
AssertionError: Unable to find any "rateints.fits" files in the inputdir: 
"/home/nicholas/science/jwst-cycle-1-and-prep/NIRSpec/Eureka_reductions/Stage1/"!

Have I missed a critical change in the run_eureka.py file, or is there another issue at work here (independent of the overlap with #125?)

**Comment by taylorbell57** [comment] 2022-04-06 23:04
Ah, sorry - in your Stage 2 ECF you'll have to specify a more detailed inputdir - so it should be something like 

```
topdir     /home/nicholas/science/jwst-cycle-1-and-prep/NIRSpec/Eureka_reductions/

inputdir   Stage1/S1_2022-04-06_nirspec_run1
outputdir  Stage2
```

**Comment by nascarsdale** [comment] 2022-04-06 23:05
ah, perfect - thank you so much!
