### ISSUE TITLE
[Bug]: WFC3 Exposure Counting

### ISSUE THREAD

**Issue by jbrande** [kevin218/Eureka#542] opened 2023-06-16 19:27 UTC
### FAQ check

- [X] Yes, I checked the FAQ and my question has not been addressed.

### Instrument

Other (any stage)

### What happened?

For HST operations, the target direct images get counted as frames in the same way the spectroscopic images do in S3, leading to an extra exposure counted per orbit compared to the spectroscopic lightcurves. When working with multiple-orbit visits, this means using the meta.orbitnum array to operate on individual orbits within the dataset will fail due to an array length mismatch. The direct images should probably be skipped when making the orbitnum array. This should also be fixed for the framenum and batchnum arrrays. 

The direct images are always the first exposure in an orbit, so maybe this is relatively simple.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment] 2023-06-16 19:33
It's been quite a while since I looked at this, but I think the direct images are supposed to be put in the cal folder.

https://eurekadocs.readthedocs.io/en/latest/ecf.html#topdir-inputdir-cal-dir

**Comment by jbrande** [comment] 2023-06-16 21:15
Ah, I tried that earlier and it didn't work. In lib/util.py, when find_fits() gets called, it will pick one of the directories to pull files from. find_fits() doesn't seem to have any WFC3 specific handling. Then, in readfiles(), meta.segment_list just gets populated with the files in whichever directory find_fits() picked, so the code that _does_ do WFC3 specific handling to search cal vs sci subfolders never gets called. So that's probably the real bug, and I only avoided it by putting all the images in the same folder.

**Comment by taylorbell57** [comment] 2023-06-16 21:18
Aha, I probably changed the find_fits() folder to recursively check subfolders since I last ran WFC3. That's likely the bug indeed

**Comment by taylorbell57** [comment] 2023-06-16 22:08
Hmm, looking back at my old WFC3 reduction from July 2022, it looks like I hadn't needed to separate the direct, wavelength calibration files from the science files. Not sure what's going on

**Comment by taylorbell57** [comment] 2023-06-16 22:33
I just re-ran those old analyses and I indeed don't need to separate the direct images. I don't get any crashes at least and the lightcurves I get are reasonable looking to me (these are public G102 observations of KELT-11b).

![fig4101_2D_LC](https://github.com/kevin218/Eureka/assets/24514122/3f2296d6-0983-41e5-a2fb-d1268ffd56e9)
![fig4102_ch0_1D_LC](https://github.com/kevin218/Eureka/assets/24514122/a7a36b5f-101b-461f-b81d-b20690fae671)

I'm on a semi-complicated mixture of the mad_axis branch and the dev/tjb branch which will fix several bugs (PRs submitted), but none of these bugs should have fixed WFC3 analyses. For reference, here's my S3 ECF (as a .txt file since GitHub doesn't trust the .ecf file extension): [S3_wfc3.txt](https://github.com/kevin218/Eureka/files/11776656/S3_wfc3.txt)

Can you clarify a bit more where you're seeing a bug/crash and copy-paste the traceback?

**Comment by jbrande** [comment] 2023-06-16 22:47
Sorry, let me clarify. Not separating the direct images from the spectroscopic files will run all the way through to S6 with no crashes, as you've just confirmed. The problem is, when you do this, the direct images get counted as exposures so your meta.orbitnum and meta.scandir arrays don't end up being the same lengths.

If the intended behavior is for the spectra and direct images to be separated, then we have a problem where Eureka! can't properly parse the directory structure. If the intended behavior is for the spectra and direct images to be in the same folder, we have a different problem where Eureka! miscounts meta.orbitnum/framenum/batchnum

**Comment by taylorbell57** [comment] 2023-06-16 22:54
The intended behaviour is indeed to keep the spectra and direct images in the same folder, since trying to separate them manually is a real pain.

Can you provide some concrete, numerical examples for the incorrect meta.orbitnum/framenum/batchnum values? I'm having trouble wrapping my head around what values are ending up wrong, and I'm having trouble determining what this might impact.

**Comment by jbrande** [comment] 2023-06-16 23:18
meta.scandir looks something like np.array([0,1,0,1,...]) for the total number of spectral exposures taken.
meta.orbitnum looks something like np.array([0,0,...1,1,...2,2,...]) for n orbits where each orbit is of length n_spectral + 1, for each spectral exposure taken per orbit and the direct image taken at the beginning of that orbit.

For example, in the HD 209458 b transit from the HST demo, taken over 5 orbits, there are 215 spectral exposures (43 per orbit), and the meta.scandir array is of length 215 and can be directly used as-is to access data from individual scan directions. (e.g. mask = meta.scandir == 0, 1, etc)
![scan_color](https://github.com/kevin218/Eureka/assets/5041139/a61f41eb-28f0-4e95-bfa7-9f6655e81272)

However, the Eureka! populated meta.orbitnum array is of length 220 (44 total per orbit, including the 5 direct images taken at the beginning of each orbit, but are not useful in the analysis past S3 centroiding IIRC), and can't be used as-is to split the data into individual orbits:
![orbit_color_improper](https://github.com/kevin218/Eureka/assets/5041139/033dd8a2-465b-4838-95d2-d589daaef1a7)
You can see that, left as-is, the extra exposure per orbit propagates through and so the first four exposures in the last orbit are marked incorrectly. I clipped the last five values off the end of the array to make the dimensions match so I could make an orbit level mask e.g. mask = meta.orbitnum == 0, 1, 2, etc.

Here's how it should look, after manually removing one value from each orbit of meta.orbitnum:
![orbit_color_proper](https://github.com/kevin218/Eureka/assets/5041139/83d00dc4-49a6-493a-8f65-2a620d3864bf)
Each orbit is now wholly its own color.

Knowing which spectral exposures belong in each orbit and scan is important for calculating orbit- and scan-level systematics, such as the sinusoidal correction to the spatial scan offset I've been working on.

If needed, we can talk more about this in the meeting Monday.

**Comment by taylorbell57** [comment] 2023-06-16 23:25
Aha, okay thanks a lot for these - this helped a lot! Unless the bug is immediately obvious to me in the next ~30 minutes, I probably won't end up having time to fix this for a week or two. Let me know here if you beat me to it

**Comment by jbrande** [comment] 2023-06-16 23:27
I have some ideas, we'll see if it happens over the weekend.

**Comment by taylorbell57** [comment] 2023-06-16 23:32
Pretty sure I just patched it with the commit referenced above, but please check that it actually works.

**Comment by jbrande** [comment] 2023-06-17 00:01
Yes! That looks like it's fixed things! 
![orbit_color_patched](https://github.com/kevin218/Eureka/assets/5041139/6635e07e-725e-4cd3-817c-09c688ab3e2e)

**Comment by taylorbell57** [comment] 2023-06-17 00:51
Wonderful! That patch will be merged soonish!

**Closed** 2023-06-17 18:15 UTC
Labels: bug, WFC3
