### ISSUE TITLE
Failed to install dependencies

### ISSUE THREAD

**Issue by ommnmm** [kevin218/Eureka#231] opened 2022-03-24 23:29 UTC
![Screen Shot 2022-03-23 at 12 53 25 PM](https://user-images.githubusercontent.com/23083481/160026024-08d3e8a5-4e47-4a0c-bffe-bf128c8f0fad.png)
![Screen Shot 2022-03-23 at 12 56 42 PM](https://user-images.githubusercontent.com/23083481/160026045-0ae922fd-a155-4a6f-8b50-25b857005867.png)

Dependencies were installed in new conda environments using pip install / pip install -r requirements.txt

MacOS 11.5.2  ,  conda 4.10.3,  processor: Intel
Note: conda 4.11.0 seems to generate worse errors -  Failed to build Eureka jwst stsci.image batman-package stsci.imagestats stsci.stimage

**Comment by taylorbell57** [comment] 2022-03-24 23:39
Hi Yucian, thanks for posting this error here so we can continue our discussion from Slack. Can you try something for me? In a terminal, please run the following lines and then post a screenshot (or several screenshots if needed) here showing your commands and the messages they print to the console? I want to isolate and understand this issue as much as possible.

`conda create -n eureka python==3.9 -y`
`conda activate eureka`
`conda info`
`which pip`
`pip install jwst==1.3.3`

**Comment by ommnmm** [comment] 2022-03-25 00:28
got error for building jwst, stsci.image, stsci.imagestats, stsci.stimage

<img width="758" alt="Screen Shot 2022-03-24 at 5 20 51 PM" src="https://user-images.githubusercontent.com/23083481/160031002-07b73df4-8f4f-4495-9fab-9d08df83494b.png">
<img width="669" alt="Screen Shot 2022-03-24 at 5 21 24 PM" src="https://user-images.githubusercontent.com/23083481/160031008-3ae3fa14-0ad0-4680-9b8f-4667bbf59ad8.png">
 
<img width="663" alt="Screen Shot 2022-03-24 at 5 21 38 PM" src="https://user-images.githubusercontent.com/23083481/160031031-e7b8adb0-99
<img width="1266" alt="Screen Shot 2022-03-24 at 5 22 40 PM" src="https://user-images.githubusercontent.com/23083481/160031049-438041f6-aa78-4834-948c-ac11d934a358.png">
3a-4c00-9e77-f2f78acdcd48.png">
<img width="1266" alt="Screen Shot 2022-03-24 at 5 24 51 PM" src="https://user-images.githubusercontent.com/23083481/160031094-a072a6cd-914c-4b69-9622-770c9c57697b.png">
<img width="1262" alt="Screen Shot 2022-03-24 at 5 25 04 PM" src="https://user-images.githubusercontent.com/23083481/160031109-d4645028-116d-41b3-9830-94e435b4a800.png">
<img width="1266" alt="Screen Shot 2022-03-24 at 5 25 19 PM" src="https://user-images.githubusercontent.com/23083481/160031119-701f0502-eaf1-44da-8f7a-a0f72b8c3bbe.png">

**Comment by taylorbell57** [comment] 2022-03-25 00:41
Okay, well that confirms that the issue is not anything to do with eureka, but an issue with jwst. I'll still try to help resolve this issue for you though since jwst is such an important part of Eureka. I'll read through all your attached screenshots in the next few days and try to figure out whether I can reproduce your error. Otherwise you'll need to open an issue on the STScI's jwst GitHub to see if they can resolve your issue (you're also welcome to do that right now if you want - their page is at https://github.com/spacetelescope/jwst/issues). It's also worth trying `pip install jwst` and see if the most recent version can install for you, but you may encounter other issues while running Eureka with that newer version as I believe at least some of the simulated data requires jwst==1.3.3 to work properly

**Comment by taylorbell57** [comment] 2022-03-29 22:39
So I was just able to reproduce a somewhat similar error message in an Ubuntu Docker container, and it seemed that there the requirement was to first run `sudo apt install gcc` after which jwst installed just fine. So it seems that you need a C compiler installed in order to pip install jwst. I'll look into this more and see if I can work out the resolution for Mac-OS (Mac-OS docker containers are nowhere near as easily run as linux).

Given my reading online, a more thorough read of your screenshots above, and a quick look through my hard drive, it seems that you might be able to resolve the issue by installing CommandLineTools (which gets installed at /Library/Developer/CommandLineTools). From what I can tell, this can be installed by running `xcode-select --install` in a terminal which should open a pop-up asking if you want to install command line developer tools. If you say yes, then you should be able to install jwst without issue. If you are comfortable doing that on your machine you can do so, but I can also try to get a Mac-OS docker running first and try that out in a safe environment to make sure it works as intended.

**Comment by taylorbell57** [comment] 2022-03-29 22:42
I just found another website of interest: https://mac.install.guide/commandlinetools/4.html

That website says that CommandLineTools will get installed anytime anyone tries to run a command themselves that requires it (apparently that excludes the `clang` call within the `pip install` command). So I and others would not have encountered this issue if we have previously manually used git, clang, gcc, cpp, or any other command that requires CommandLineTools. So perhaps the simplest and safest feeling way to install CommandLineTools is to do `git status` in a terminal which should then open that pop-up asking you to install command line developer tools. @ommnmm can you please try that out?

**Comment by taylorbell57** [comment] 2022-04-05 01:13
Hearing nothing and strongly suspecting that the method described above (and now explained [on our FAQ page](https://eurekadocs.readthedocs.io/en/latest/faq.html#issues-installing-or-importing-jwst)) should resolve the issue, I am going to close the issue now. If you still can't install the jwst package, please let us know here (so we know this is still an issue) but you'll have to contact the jwst package developers at https://github.com/spacetelescope/jwst/issues to work out a solution with them

**Closed by taylorbell57** 2022-04-05 01:13 UTC
Labels: bug
